language: node_js
node_js:
- v5
- v4
- '0.12'
- '0.10'
deploy:
  provider: npm
  email: daniel.hoisel@prodest.es.gov.br
  api_key:
    secure: fQlDeX1M9oqu88FIpxQKoT86RW0QSb3Py0+ThuizLERnElPqJWY+wf4c5UrO2BXCFY++AmAT/shgICsb80lMEWkBtK9eM3pA1jnI+PZoBBfxz3KtsJC1eO+V8xHSa2K0KCW0M6FbLNWo/CZD1v7JNw6tMRtlNTsfxtYYFHKTrYZSX1MKAlb7/FkZL0bPDaXdD8mdv7yfKphAdiDRdW6Q3MidhLph4OYFg58fr/SMIKtsAr8QOnmxy/8RbTRs0fPyDUSDkvWvrkSCQjmkKcnZyC1kU1/PNxSyXgoSgMpKcMrGrCXh/MBXUSL+RM6nEN1EsPm/bJ/NrMCbvHKFV25JESCat2ONxloNHzklIVo41peFTCdHauCq6de4NFdwY3hE10aHHeVMHzHGxSXPB1J4oPp2K8/v2cf2M5QqgYgMJWufmyBw7IfPytVrHeHUX1/i74wjTJEJn5KgjglvlKDoB+qkKmREYiuEeyz+jBhykMfCotEcf4Kxv31qw+sNvd6KLUEvNNX0CzqeeqhGAKZITopivXm/D3EIeXVfhBy3pqr31VF1DSqtcCFGZ29zgNoeYxrfrFYu82cRI7oNyTX3rjAN40NB6zn+tuFxejnq0MRiN4UWuv70B6+bSG+hp+a573jPBfBzFatSIyIXDkZWamw8Zmr81MtTP1Sv5IRQrPM=
  on:
    tags: true
